[tool.poetry]
name = "cve-api"
version = "0.1.0"
description = ""
authors = ["Maksim Perkovskiy <m.perkovskiy@godeltech.com>"]
readme = "README.md"
packages = [{include = "cve_api"}]

[tool.poetry.dependencies]
python = "^3.10"
flask = "2.3.2"
sqlalchemy = "2.0.12"
dacite = "1.8.0"
pydantic = "1.10.7"
elasticsearch = "8.7.0"
dependency-injector = {extras = ["yaml"], version = "^4.41.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
